import type { Metadata } from "next";
import Link from "next/link";
import { Robot } from "@/components/robot/Robot";
import { ArrowRightIcon, ChatIcon, HandIcon, SoundIcon, SparkIcon } from "@/components/ui/Icons";

export const metadata: Metadata = { title: "Tentang", description: "Tentang Reihan.online dan REIA, eksperimen AI dan teknologi kreatif interaktif." };

export default function AboutPage() {
  return <main className="about-page"><section className="about-hero section-shell"><div><p className="kicker">TENTANG REIHAN.ONLINE</p><h1>Tempat teknologi<br />terasa <span>lebih manusia.</span></h1><p>Reihan.online adalah playground digital eksperimental yang mempertemukan artificial intelligence, suara, computer vision, musik, dan interaksi manusia-komputer dalam satu pengalaman.</p><div className="button-row"><Link className="button button--primary" href="/reia">Kenalan dengan REIA <ArrowRightIcon /></Link></div></div><div className="about-hero__robot"><Robot state="happy" /></div></section><section className="about-manifesto"><div className="section-shell"><p>“Ini bukan cuma chatbot. REIA dirancang sebagai robot kecil interaktif yang hidup di browser—bisa diajak ngobrol, mendengar, berbicara, dan ikut bermain musik.”</p></div></section><section className="about-pillars section-shell"><div><SparkIcon /><strong>Artificial Intelligence</strong><p>Percakapan natural berbahasa Indonesia dengan identitas yang konsisten.</p></div><div><SoundIcon /><strong>Audio & Voice</strong><p>Suara, synthesizer, ritme, dan respons audio yang dibuat langsung di browser.</p></div><div><HandIcon /><strong>Computer Vision</strong><p>Gerakan tangan dibaca lokal untuk mengubah pitch, nada, dan efek musik.</p></div><div><ChatIcon /><strong>Human Interaction</strong><p>Teknologi yang mudah dipahami, playful, dan tetap menghargai privasi.</p></div></section><section className="about-credit section-shell"><p className="kicker">CREATED BY REIHAN</p><h2>Eksperimen kecil.<br />Kemungkinan besar.</h2><p>Dibuat oleh Reihan sebagai karya creative technology yang akan terus berkembang—dari browser menuju kemungkinan robot fisik, perangkat interaktif, dan pengalaman digital baru.</p></section></main>;
}
